server:
  port: 1016
mysql:
  host: 127.0.0.1
  port: 3306
  root: root
  password: hwqq1220
  database: travel_database
  loc: Asia/Shanghai

wx:
  appID: wx477cc96f24a1a742
  appSecret: a66881199b407098b40090f3ad6f7216