server:
  port: 1016
mysql:
  host: 127.0.0.1
  port: 3306
  root:
  password: 
  database: travel_database
  loc: Asia/Shanghai

wx:
  appID: 
  appSecret: 

baidu:
  ak: ""
  region: 

admin:
  token: ""
